version: '3.8'
services:
  trainer:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8888:8888"
      - "6006:6006"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    gpus: all
